{% set name = "repo-review" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scientific-python/repo-review/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ae3ea26e22984f30418dcde3adfc0781c0ef429f9c91964b75c585ef85e36676

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - repo-review = repo_review.__main__:main

requirements:
  host:
    - hatchling
    - hatch-vcs
    - python >=3.10
    - pip
  run:
    - click
    - markdown-it-py
    - python >=3.10
    - pyyaml
    - rich
    - rich-click
    - tomli
    - typing-extensions

test:
  imports:
    - repo_review
    - repo_review.fixtures
    - repo_review.schema
  source_files:
    - docs
    - tests
    - README.md
    - LICENSE
    - noxfile.py
    - pyproject.toml
    - .github
    - .pre-commit-config.yaml
    - .readthedocs.yaml
  requires:
    - pip
    - pytest
    - sp-repo-review
    - validate-pyproject >=0.14
  commands:
    - pip check
    - repo-review --help
    - validate-pyproject -E repo-review --help
    - mkdir src
    - ls
    - pytest -ra
  downstreams:
    - sp-repo-review

about:
  home: https://github.com/scientific-python/repo-review
  summary: 'This is a framework for building checks designed to check to see if a repository follows guidelines'
  description: |
    This is a framework for building checks designed to check to see if a repository follows
    guidelines. By itself, it does nothing - it requires at least one plugin to be installed.

    With one or more plugins, it will produce a list of results - green checkmarks mean this
    rule is followed, red x’s mean the rule is not. A yellow warning sign means that the check
    was skipped because a previous required check failed. Four output formats are supported;
    rich, svg, html, and json.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://repo-review.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - henryiii
    - MementoRC
